set nocompatible        " enter the current millenium
syntax enable
set termguicolors       " enable true colors support
let ayucolor="dark"     " for dark version of theme
colorscheme ayu
filetype plugin on
set tabstop=2           " number of visual spaces per TAB
set softtabstop=2       " number of spaces in tab when editing
set expandtab           " tabs are spaces
set number              " show line numbers
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set encoding=utf-8
set linebreak           " avoid wrapping a line in the middle of a word
set wrap                " line wrapping
set title               " window’s title, reflecting the file currently being edited
set confirm             " display a confirmation dialog when closing an unsaved file
set path+=**            " search down into subfolders
 
:imap <C-k> <Esc>
map <C-o> :NERDTreeToggle<CR>
map <Leader> <Plug>(easymotion-prefix)
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

