" set compatibility to Vim only.
set nocompatible

" enable true colors support
set termguicolors

" For plug-ins to load correctly.
filetype plugin indent on

" Turn off modelines
set modelines=0

" number of visual spaces per TAB
set tabstop=2

" number of spaces in tab when editing
set softtabstop=2

" number of spaces when shifting
set shiftwidth=2

" tabs are spaces
set expandtab

" show line numbers
set number

" visual autocomplete for command menu
set wildmenu

" redraw only when we need to.
set lazyredraw

" search as characters are entered
set incsearch

" highlight matches
set hlsearch

" search as characters are entered
set incsearch

" highlight matches
set hlsearch

" encoding
set encoding=utf-8

" avoid wrapping a line in the middle of a word
set linebreak

" line wrapping
set wrap

" window’s title, reflecting the file currently being edited
set title

" display a confirmation dialog when closing an unsaved file
set confirm

" search down into subfolders
set path+=**

" display 5 lines above/below the cursor when scrolling with a mouse.
set scrolloff=5

" fixes common backspace problems
set backspace=indent,eol,start 

" speed up scrolling
set ttyfast

" status bar
set laststatus=2

" display options
set showmode
set showcmd

" display different types of white spaces.
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.

" set status line display
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}


" Vim's auto indentation feature does not work properly with text copied from outisde of Vim. Press the <F2> key to toggle paste mode on/off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>


syntax enable
set background=dark
colorscheme material-theme

map <C-o> :NERDTreeToggle<CR>
map <Leader> <Plug>(easymotion-prefix)

" for easier tab switching
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
